name: "Access Secrets"

on: [pull_request_target]

jobs:
  access-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Use secret
        env:
          SECRET_VALUE: ${{ secrets.MY_SECRET }}
        run: echo $SECRET_VALUE
